# .github/workflows/backend-ci.yml
name: Backend CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'trackz-api/**' # Só roda se houver mudanças no backend

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./trackz-api # Define o diretório de trabalho para todos os comandos

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8 # ou a versão do pnpm que você usa

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'trackz-api/pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm lint

      - name: Run Unit Tests
        run: pnpm test

      - name: Build Project
        run: pnpm build