# .github/workflows/frontend-ci.yml
name: Frontend CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    # A seção 'paths' foi removida

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./trackz-web

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'trackz-web/package-lock.json'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test -- --watchAll=false

      - name: Build Project
        run: npm run build
